version: '3.8'
services:
  booking:
    image: danieldawsonjensen/upload-image:latest
    environment:
      - ImagePath=/srv/images
    ports:
      - "5001:80"
    networks:
      - default
    volumes:
      - images:/srv/images

  plan:
    image: danieldawsonjensen/upload-image:latest
    environment:
      - ImagePath=/srv/images
    ports:
      - "5001:80"
    networks:
      - default
    volumes:
      - images:/srv/images
    
volumes:
 images:
  external: false
networks:
 default:
  driver: bridge
  name: mitnet